### ISSUE TITLE
example config for monthly?

### ISSUE THREAD

**Issue by shapr** [volhovM/orgstat#8]
Thanks for writing orgstat, I'm able to use the example config to get weekly stats, but I can't figure out how to get monthly stats. Is there an example that demonstrates this?

**Comment by volhovm** [comment]
What exactly output do you use? Template (summary) or timeline?
@shapr In any case, you should just change the reports you're using.

For example, to generate a template output for the previous month:
```
reports:
  - name: prevMonth
    range: month-1
outputs:
  - name: prevMonthTimeline
    report: prevMonth
    type: timeline
```
